In [12]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from pyecharts.charts import Boxplot
from pyecharts import options as opts

D:\DevelopmentTools\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [2]:
# 读入需要进行可视化的数据
data = pd.read_csv('F:\Codes\ProductionPractice\OutputData\ExcelData3.csv')
data.head()

,学号,考生姓名,科目名称,性别,专业,年份,编程年份,国家级一等奖,国家级二等奖,国家级三等奖,国家级优秀奖,省部级一等奖,省部级二等奖,省部级三等奖,省部级优秀奖,OJ提交数,OJ正确数,OJ准确率,获奖类别
0,2016014537,金任任,0,1,1,2019,3,0,0,0,1,1,0,0,0,355,133,0.374648,2
1,2015014309,闫楠,1,1,1,2018,3,0,1,0,0,1,1,0,0,0,0,0.000000,1
2,2015014391,郭一挺,1,1,1,2018,3,0,0,0,0,0,1,1,0,0,0,0.000000,1
3,2017040381,刘俊宇,0,1,1,2018,1,0,0,0,0,0,0,0,0,46,34,0.739130,1
4,2016014281,刘权达,0,1,1,2018,2,0,0,0,0,0,1,0,0,77,30,0.389610,2

In [3]:
# 去掉提交数为0的数据
data = data[data['OJ提交数'] != 0]
data.head()

,学号,考生姓名,科目名称,性别,专业,年份,编程年份,国家级一等奖,国家级二等奖,国家级三等奖,国家级优秀奖,省部级一等奖,省部级二等奖,省部级三等奖,省部级优秀奖,OJ提交数,OJ正确数,OJ准确率,获奖类别
0,2016014537,金任任,0,1,1,2019,3,0,0,0,1,1,0,0,0,355,133,0.374648,2
3,2017040381,刘俊宇,0,1,1,2018,1,0,0,0,0,0,0,0,0,46,34,0.739130,1
4,2016014281,刘权达,0,1,1,2018,2,0,0,0,0,0,1,0,0,77,30,0.389610,2
5,2017060374,罗朝旭,0,1,1,2018,0,0,0,0,0,0,0,0,0,112,92,0.821429,2
6,2015014386,赵博宇,0,1,1,2018,3,0,0,0,0,0,0,1,0,270,111,0.411111,2

In [4]:
# 描述性数据统计
data.loc[:, ['OJ正确数', 'OJ提交数', 'OJ准确率']].describe()

            OJ正确数        OJ提交数       OJ准确率
count  207.000000   207.000000  207.000000
mean   114.270531   228.821256    0.535356
std    110.847198   228.184225    0.156157
min      0.000000     1.000000    0.000000
25%     34.000000    63.000000    0.455064
50%     76.000000   142.000000    0.513274
75%    166.000000   341.000000    0.602439
max    506.000000  1054.000000    1.000000

In [11]:
# 进行y轴数据的准备
y_data = [
    data['OJ正确数'],
    data['OJ提交数']
]

# 绘制箱型图
box = (
    Boxplot().
    add_xaxis(['OJ正确数', 'OJ提交数']).
    add_yaxis(series_name="数量", y_axis=Boxplot.prepare_data(y_data)).
    set_global_opts(
        init_opts=opts.InitOps(
            page_title='正样本oj正确数与提交数箱型图'
        ),
        toolbox_opts=opts.ToolboxOpts(),
        title_opts=opts.TitleOpts(title='正样本oj正确数与提交数箱型图')
    )
)
box.render()

[0      133
3       34
4       30
5       92
6      111
      ...
222     69
223     21
224    215
225      2
226     34
Name: OJ正确数, Length: 207, dtype: int64, 0      355
3       46
4       77
5      112
6      270
      ...
222    164
223     47
224    500
225      5
226     93
Name: OJ提交数, Length: 207, dtype: int64]

D:\DevelopmentTools\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\DevelopmentTools\Anaconda3\lib\site-packages\pyecharts\charts\chart.py:14: PendingDeprecationWarning: pyecharts 所有图表类型将在 v1.9.0 版本开始强制使用 ChartItem 进行数据项配置 :)
  super().__init__(init_opts=init_opts)

'F:\\Codes\\ProductionPractice\\Project\\render.html'